# Jekyll config

title: ren's stuff
description: hi! i'm ren, i like making things occasionally
author: Red Penguin

url: "https://redpengu.in"

# Build settings
plugins:
  - jekyll-target-blank
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:title
    sort_by: date
  posts:
    output: true
    permalink: /blog/:year/:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: project
      icon: fa-solid fa-cube
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
